costs/spending/urls.py
from django.urls import path
from costs.spending import views


urlpatterns = [
    path('create/', views.SpendingCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.SpendingUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.SpendingDeleteView.as_view(), name='delete'),
    path('', views.IndexSpendingsView.as_view(), name='index'),
    path('diagram/', views.CircleDiagramView.as_view(), name='diagram'),
    path('diagram/exact', views.CircleDefinView.as_view(), name='exact')
]

costs/urls.py
from django.contrib import admin
from django.urls import path, include
from costs import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexMainView.as_view(), name='main'),
    path('users/', include(('costs.users.urls', 'users'), namespace='users')),
    path('spending/', include(('costs.spending.urls', 'spending'), namespace='spending'))
]

costs/users/urls.py
from django.urls import path
from costs.users import views

urlpatterns = [path('login/', views.LoginPerson.as_view(), name='login'),
               path('create/', views.CreatePerson.as_view(), name='create'),
               path('logout/', views.logout_user, name='logout'),
               path('<int:pk>/update/', views.PersonUpdate.as_view(), name='update'),
               path('<int:pk>/delete/', views.PersonDelete.as_view(), name='delete'),
               path('<int:pk>/show/', views.PersonShowView.as_view(), name='show')]

costs/spending/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

    
class Spending(models.Model):
    price = models.PositiveIntegerField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='spendings')
    category = models.CharField(max_length=75, default=None)
    timestamp = models.DateField(auto_now_add=True)

costs/spending/forms.py
from django import forms
from costs.spending import models
from costs.spending.models import Spending

class SpendingCreateForm(forms.ModelForm):
    CHOICES = [
        ('Супермаркеты', 'Супермаркеты'), 
        ('Коммунальные платежи, связь, интернет', 'Коммунальные платежи, связь, интернет'),
        ('Погашение кредитов', 'Погашение кредитов'), 
        ('Отдых и развлечения', 'Отдых и развлечения'),
        ('Здоровье и красота', 'Здоровье и красота'),
        ('Транспорт', 'Транспорт'), 
        ('Прочее', 'Прочее')
    ]
    
    price = forms.IntegerField(label='Цена', widget=forms.TextInput(attrs={'class': 'form-control form-control-lg'}))
    category = forms.ChoiceField(label='Категория', choices=CHOICES, widget=forms.Select(attrs={'class': 'form-select'}))
    
    class Meta:
        model = Spending
        fields = [
            'price',
            'category'
        ]

costs/users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth import get_user_model

class AuthPersonForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-control form-control-lg'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control form-control-lg'}))
    
    class Meta:
        model = User
        fields = ['email',
                  'password'
                  ]
        
        
class RegisterPersonForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-control form-control-lg'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control form-control-lg'}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-control form-control-lg'}))
    email = forms.CharField(label='Email', widget=forms.TextInput(attrs={'class': 'form-control form-control-lg'}))
    
    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'password1', 'password2']
        
    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Такой E-mail уже существует!")
        return email
    
class PersonUpdateForm(forms.ModelForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-control form-control-lg'}))
    email = forms.CharField(label='Email', widget=forms.TextInput(attrs={'class': 'form-control form-control-lg'}))
    
    class Meta:
        model = User
        fields = ['username', 'email']

costs/spending/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView
from costs.spending.forms import *
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth import logout
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from costs.users.mixins import RightUserMixin
from costs.spending.mixins import AuthorAccessMixin
from costs.spending.models import *
from django.contrib.auth.mixins import LoginRequiredMixin
from costs.spending.filters import LeadEntriesFilter
from datetime import date
from costs.spending.func import prepare

class SpendingCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    login_url = reverse_lazy('users:login')
    success_message = 'Трата добавлена'
    template_name = 'spending/create.html'
    form_class = SpendingCreateForm
    success_url = reverse_lazy('spending:index')
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    
class SpendingUpdateView(AuthorAccessMixin, SuccessMessageMixin, UpdateView):
    login_url = reverse_lazy('users:login')
    success_message = 'Трата изменена'
    template_name = 'spending/update.html'
    form_class = SpendingCreateForm
    success_url = reverse_lazy('spending:index')
    model = Spending
    
class SpendingDeleteView(AuthorAccessMixin, SuccessMessageMixin, DeleteView):
    model = Spending
    template_name = 'spending/delete.html'
    login_url = reverse_lazy('users:login')
    success_url = reverse_lazy('spending:index')
    success_message = 'Трата удалена'
    
class IndexSpendingsView(LoginRequiredMixin, View):
    login_url = reverse_lazy('users:login')
    def get(self, request, *args, **kwargs):
        f = LeadEntriesFilter(request.GET, queryset=Spending.objects.filter(author=request.user))
        return render(request, 'spending/index.html', {'f': f})
    
class CircleDiagramView(LoginRequiredMixin, View):
    login_url = reverse_lazy('users:login')
    def get(self, request, *args, **kwargs):
        author = request.user
        date_now = date.today()
        if date_now.month == 1:
            date_old = date(date_now.year - 1, 12, 1)
        else:
            date_old = date(date_now.year, date_now.month - 1, 1)
            
        qs_now = Spending.objects.filter(author=author).filter(timestamp__year=date_now.year, timestamp__month=date_now.month)
        qs_old = Spending.objects.filter(author=author).filter(timestamp__year=date_old.year, timestamp__month=date_old.month)
        
        d_now = prepare(qs_now)
        d_old = prepare(qs_old)
        
        
        labels_now, labels_old = list(d_now.keys()), list(d_old.keys())
        data_now, data_old = list(d_now.values()), list(d_old.values())
        
        
        return render(request, 'spending/diagram.html', {'labels_now': labels_now, 'data_now': data_now, 
                                             'labels_old': labels_old, 'data_old': data_old})
        
class CircleDefinView(LoginRequiredMixin, View):
    login_url = reverse_lazy('users:login')
    def get(self, request, *args, **kwargs):
        f = LeadEntriesFilter(request.GET, queryset=Spending.objects.filter(author=request.user))
        d = prepare(f.qs)
        labels, data = list(d.keys()), list(d.values())
        return render(request, 'spending/diagram_date.html', {'f': f, 'labels': labels, 'data':data})

costs/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView
from costs.users.forms import *
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth import logout
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from costs.users.mixins import RightUserMixin

class LoginPerson(SuccessMessageMixin, LoginView):
    form_class = AuthPersonForm
    template_name = 'users/login.html'
    success_url = reverse_lazy('main')
    login_url = reverse_lazy('users:login')
    success_message = 'Вы авторизованы'
    
    def get_success_url(self):
        return self.success_url
    
class CreatePerson(SuccessMessageMixin, CreateView):
    template_name = 'users/create.html'
    form_class = RegisterPersonForm
    success_url = reverse_lazy('users:login')
    success_message = 'Пользователь создан'
    
def logout_user(request):
    if request.user.is_authenticated:
        logout(request)
        messages.success(request, 'Пользователь вышел')
        return redirect(reverse_lazy('main'))
    else:
        messages.error(request, 'Вы не авторизованы')
        return redirect(reverse_lazy('main'))
    
    
class PersonUpdate(RightUserMixin, SuccessMessageMixin, UpdateView):
    model = User
    form_class = PersonUpdateForm
    template_name = 'users/update.html'
    success_url = reverse_lazy('main')
    success_message = 'Пользователь изменен'
    login_url = reverse_lazy('users:login')
    
class PersonDelete(RightUserMixin, SuccessMessageMixin, DeleteView):
    model = User
    template_name = 'users/delete.html'
    success_message = 'Пользователь удален'
    login_url = reverse_lazy('users:login')
    success_url = reverse_lazy('main')
    
class PersonShowView(View):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            if request.user.id == kwargs['pk']:
                return render(request, 'users/show.html', {'user': request.user})
        messages.error(request, 'Необходимо войти')
        return redirect(reverse_lazy('main'))

costs/views.py
from django.shortcuts import render
from django.views import View

class IndexMainView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'main.html')

costs/templates/base.html
<html lang="ru">
    <head>
        {% load bootstrap5 %}
        {% bootstrap_css %}
        {% bootstrap_javascript %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Система учета расходов</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/pricing/">

    

    <!-- Bootstrap core CSS -->
<link href="/docs/5.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    {% load static %}
    <!-- Custom styles for this template -->
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
  </head>
  <body>
    

<div class="container py-3">
  <header>
    <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center text-dark text-decoration-none" previewlistener="true">
        <span class="fs-4">Система расходов</span>
      </a>

      <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
        <a class="me-3 py-2 text-dark text-decoration-none" href="{% url "spending:diagram" %}">Диаграммы</a>
        <a class="me-3 py-2 text-dark text-decoration-none" href="{% url "spending:index" %}">Расходы</a>
        {% if request.user.is_authenticated %}
        <a class="me-3 py-2 text-dark text-decoration-none" href="{% url "users:show" pk=request.user.id %}">{{ request.user.username }}</a>
        <a class="py-2 text-dark text-decoration-none" href="{% url "users:logout" %}">Выйти</a>
        {% else %}
        <a class="me-3 py-2 text-dark text-decoration-none" href="{% url "users:create" %}">Регистрация</a>
        <a class="py-2 text-dark text-decoration-none" href="{% url "users:login" %}">Вход</a>
        {% endif %}
      </nav>
    </div>

    
  </header>

  <main>
    {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
    {% endfor %}
</ul>
{% endif %}
    {% block content %}{% endblock content %}
  </main>

  <footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
      <div class="col-12 col-md">
        <small class="d-block mb-3 text-muted">© 2023</small>
      </div>
      <div class="col-6 col-md">
        <h5>Обо мне</h5>
        <ul class="list-unstyled text-small">
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Телеграмм</a></li>
        </ul>
      </div>
    </div>
  </footer>
</div>


    
  

</body></html>

costs/templates/base_create.html
{% extends "base.html" %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}
{% block title %}{% endblock title %}
<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p ><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit" class="btn btn-primary">Создать</button></p>
</form>
{% endblock content %}

costs/templates/base_delete.html
{% extends "base.html" %}
{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% block content %}
<h1 class="h1 my-4">
    {% block title_name %}{% endblock title_name %}
</h1>

<p>
    {% block description %}{% endblock description %}
</p>

<form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-outline-danger" value="Удалить">
</form>
{% endblock content %}

costs/templates/base_update.html
{% extends "base.html" %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}
{% block title %}{% endblock title %}
<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p ><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit" class="btn btn-primary">Изменить</button></p>
</form>
{% block delete %}{% endblock delete %}
{% endblock content %}

costs/templates/main.html
{% extends "base.html" %}

{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}
<div class="pricing-header p-3 pb-md-4 mx-auto text-center">
    <h1 class="display-4 fw-normal">Расходы</h1>
    <p class="fs-5 text-muted">Добро пожаловать в систему учета расходов. Управляйте своими финансами более эффективно и осознанно с помощью этой системы.</p>
  </div>
{% if request.user.is_authenticated %}
<a type="button" class="w-100 btn btn-lg btn-outline-primary" href='{% url "spending:index" %}'>Начать</a>
{% else %}
<a type="button" class="w-100 btn btn-lg btn-outline-primary" href='{% url "users:login" %}'>Начать</a>
{% endif %}
{% endblock content %}