costs/spending/urls.py
from django.urls import path
from costs.spending import views


urlpatterns = [
    path('create/', views.SpendingCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.SpendingUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.SpendingDeleteView.as_view(), name='delete'),
    path('', views.IndexSpendingsView.as_view(), name='index'),
    path('diagram/', views.CircleDiagramView.as_view(), name='diagram'),
    path('diagram/exact', views.CircleDefinView.as_view(), name='exact')
]

costs/urls.py
from django.contrib import admin
from django.urls import path, include
from costs import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexMainView.as_view(), name='main'),
    path('users/', include(('costs.users.urls', 'users'), namespace='users')),
    path('spending/', include(('costs.spending.urls', 'spending'), namespace='spending'))
]

costs/users/urls.py
from django.urls import path
from costs.users import views

urlpatterns = [path('login/', views.LoginPerson.as_view(), name='login'),
               path('create/', views.CreatePerson.as_view(), name='create'),
               path('logout/', views.logout_user, name='logout'),
               path('<int:pk>/update/', views.PersonUpdate.as_view(), name='update'),
               path('<int:pk>/delete/', views.PersonDelete.as_view(), name='delete'),
               path('<int:pk>/show/', views.PersonShowView.as_view(), name='show')]

costs/spending/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

    
class Spending(models.Model):
    price = models.PositiveIntegerField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='spendings')
    category = models.CharField(max_length=75, default=None)
    timestamp = models.DateField(auto_now_add=True)

costs/spending/forms.py
from django import forms
from costs.spending import models
from costs.spending.models import Spending

class SpendingCreateForm(forms.ModelForm):
    CHOICES = [
        ('Супермаркеты', 'Супермаркеты'), 
        ('Коммунальные платежи, связь, интернет', 'Коммунальные платежи, связь, интернет'),
        ('Погашение кредитов', 'Погашение кредитов'), 
        ('Отдых и развлечения', 'Отдых и развлечения'),
        ('Здоровье и красота', 'Здоровье и красота'),
        ('Транспорт', 'Транспорт'), 
        ('Прочее', 'Прочее')
    ]
    
    price = forms.IntegerField(label='Цена', widget=forms.TextInput(attrs={'class': 'form-control form-control-lg'}))
    category = forms.ChoiceField(label='Категория', choices=CHOICES, widget=forms.Select(attrs={'class': 'form-select'}))
    
    class Meta:
        model = Spending
        fields = [
            'price',
            'category'
        ]

costs/users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth import get_user_model

class AuthPersonForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-control form-control-lg'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control form-control-lg'}))
    
    class Meta:
        model = User
        fields = ['email',
                  'password'
                  ]
        
        
class RegisterPersonForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-control form-control-lg'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control form-control-lg'}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-control form-control-lg'}))
    email = forms.CharField(label='Email', widget=forms.TextInput(attrs={'class': 'form-control form-control-lg'}))
    
    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'password1', 'password2']
        
    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Такой E-mail уже существует!")
        return email
    
class PersonUpdateForm(forms.ModelForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-control form-control-lg'}))
    email = forms.CharField(label='Email', widget=forms.TextInput(attrs={'class': 'form-control form-control-lg'}))
    
    class Meta:
        model = User
        fields = ['username', 'email']

costs/spending/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView
from costs.spending.forms import *
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth import logout
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from costs.users.mixins import RightUserMixin
from costs.spending.mixins import AuthorAccessMixin
from costs.spending.models import *
from django.contrib.auth.mixins import LoginRequiredMixin
from costs.spending.filters import LeadEntriesFilter
from datetime import date
from costs.spending.func import prepare

class SpendingCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    login_url = reverse_lazy('users:login')
    success_message = 'Трата добавлена'
    template_name = 'spending/create.html'
    form_class = SpendingCreateForm
    success_url = reverse_lazy('spending:index')
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    
class SpendingUpdateView(AuthorAccessMixin, SuccessMessageMixin, UpdateView):
    login_url = reverse_lazy('users:login')
    success_message = 'Трата изменена'
    template_name = 'spending/update.html'
    form_class = SpendingCreateForm
    success_url = reverse_lazy('spending:index')
    model = Spending
    
class SpendingDeleteView(AuthorAccessMixin, SuccessMessageMixin, DeleteView):
    model = Spending
    template_name = 'spending/delete.html'
    login_url = reverse_lazy('users:login')
    success_url = reverse_lazy('spending:index')
    success_message = 'Трата удалена'
    
class IndexSpendingsView(LoginRequiredMixin, View):
    login_url = reverse_lazy('users:login')
    def get(self, request, *args, **kwargs):
        f = LeadEntriesFilter(request.GET, queryset=Spending.objects.filter(author=request.user))
        return render(request, 'spending/index.html', {'f': f})
    
class CircleDiagramView(LoginRequiredMixin, View):
    login_url = reverse_lazy('users:login')
    def get(self, request, *args, **kwargs):
        author = request.user
        date_now = date.today()
        if date_now.month == 1:
            date_old = date(date_now.year - 1, 12, 1)
        else:
            date_old = date(date_now.year, date_now.month - 1, 1)
            
        qs_now = Spending.objects.filter(author=author).filter(timestamp__year=date_now.year, timestamp__month=date_now.month)
        qs_old = Spending.objects.filter(author=author).filter(timestamp__year=date_old.year, timestamp__month=date_old.month)
        
        d_now = prepare(qs_now)
        d_old = prepare(qs_old)
        
        
        labels_now, labels_old = list(d_now.keys()), list(d_old.keys())
        data_now, data_old = list(d_now.values()), list(d_old.values())
        
        
        return render(request, 'spending/diagram.html', {'labels_now': labels_now, 'data_now': data_now, 
                                             'labels_old': labels_old, 'data_old': data_old})
        
class CircleDefinView(LoginRequiredMixin, View):
    login_url = reverse_lazy('users:login')
    def get(self, request, *args, **kwargs):
        f = LeadEntriesFilter(request.GET, queryset=Spending.objects.filter(author=request.user))
        d = prepare(f.qs)
        labels, data = list(d.keys()), list(d.values())
        return render(request, 'spending/diagram_date.html', {'f': f, 'labels': labels, 'data':data})

costs/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView
from costs.users.forms import *
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth import logout
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from costs.users.mixins import RightUserMixin

class LoginPerson(SuccessMessageMixin, LoginView):
    form_class = AuthPersonForm
    template_name = 'users/login.html'
    success_url = reverse_lazy('main')
    login_url = reverse_lazy('users:login')
    success_message = 'Вы авторизованы'
    
    def get_success_url(self):
        return self.success_url
    
class CreatePerson(SuccessMessageMixin, CreateView):
    template_name = 'users/create.html'
    form_class = RegisterPersonForm
    success_url = reverse_lazy('users:login')
    success_message = 'Пользователь создан'
    
def logout_user(request):
    if request.user.is_authenticated:
        logout(request)
        messages.success(request, 'Пользователь вышел')
        return redirect(reverse_lazy('main'))
    else:
        messages.error(request, 'Вы не авторизованы')
        return redirect(reverse_lazy('main'))
    
    
class PersonUpdate(RightUserMixin, SuccessMessageMixin, UpdateView):
    model = User
    form_class = PersonUpdateForm
    template_name = 'users/update.html'
    success_url = reverse_lazy('main')
    success_message = 'Пользователь изменен'
    login_url = reverse_lazy('users:login')
    
class PersonDelete(RightUserMixin, SuccessMessageMixin, DeleteView):
    model = User
    template_name = 'users/delete.html'
    success_message = 'Пользователь удален'
    login_url = reverse_lazy('users:login')
    success_url = reverse_lazy('main')
    
class PersonShowView(View):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            if request.user.id == kwargs['pk']:
                return render(request, 'users/show.html', {'user': request.user})
        messages.error(request, 'Необходимо войти')
        return redirect(reverse_lazy('main'))

costs/views.py
from django.shortcuts import render
from django.views import View

class IndexMainView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'main.html')

costs/templates/spending/create.html
{% extends "base_create.html" %}

{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block title %}
<h1>
Создать трату
</h1>
{% endblock title %}

costs/templates/spending/delete.html
{% extends "base_delete.html" %}


{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block title_name %}
Удалить трату
{% endblock title_name %}

costs/templates/spending/diagram.html
{% extends "base.html" %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}
{% if data_now %}
<form action="{% url "spending:exact"%}">
  <button type="submit" class="btn btn-primary" style="margin:0 10px;">Выбрать промежуток</button>
</form>
<h1>
    Текущий месяц
</h1>
<div id="container" style="width: 75%;">
    <canvas id="pie-chart"></canvas>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
  <script>

    var config = {
      type: 'pie',
      data: {
        datasets: [{
          data: {{ data_now|safe }},
          backgroundColor: [
          'rgb(255, 99, 132)',
          'rgb(54, 162, 235)',
          'rgb(255, 205, 86)',
          'rgb(158, 0, 0)',
          'rgb(189, 255, 0)',
          'rgb(6, 4, 255)',
          'rgb(6, 160, 95)'
          ],
          label: 'Costs'
        }],
        labels: {{ labels_now|safe }}
      },
      options: {
        responsive: true
      }
    };

    window.onload = function() {
      var ctx = document.getElementById('pie-chart').getContext('2d');
      window.myPie = new Chart(ctx, config);
    };
</script>
{% else %}
<h1>
    Информация о текущем месяце отстутствует
</h1>
{% endif %}
{% endblock content %}

costs/templates/spending/diagram_date.html
{% extends "base.html" %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}
<form method="get">
    {{ f.form.as_p }}
    <input type="submit" value='Применить фильтр' class="btn btn-primary"/>
  </form>
{% if data %}
<div id="container" style="width: 75%;">
    <canvas id="pie-chart"></canvas>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
  <script>

    var config = {
      type: 'pie',
      data: {
        datasets: [{
          data: {{ data|safe }},
          backgroundColor: [
          'rgb(255, 99, 132)',
          'rgb(54, 162, 235)',
          'rgb(255, 205, 86)',
          'rgb(158, 0, 0)',
          'rgb(189, 255, 0)',
          'rgb(6, 4, 255)',
          'rgb(6, 160, 95)'
          ],
          label: 'Costs'
        }],
        labels: {{ labels|safe }}
      },
      options: {
        responsive: true
      }
    };

    window.onload = function() {
      var ctx = document.getElementById('pie-chart').getContext('2d');
      window.myPie = new Chart(ctx, config);
    };
</script>
{% else %}
<h1>
    Информация о данном отрезке отстутствует
</h1>
{% endif %}
{% endblock content %}

costs/templates/spending/index.html
{% extends "base.html" %}
{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% block content %}
<h1 class="h1 my-4">
    Список трат
</h1>
<a class="btn btn-primary mb-3" href="{% url "spending:create" %}">Создать трату</a>
<div class="card">
  <div class="card-body">
<form method="get">
  {{ f.form.as_p }}
  <input type="submit" value='Применить фильтр' class="btn btn-primary"/>
</form>
</div>
</div>

<table class="table">
    <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">Стоимость</th>
        <th scope="col">Категория</th>
        <th scope="col">Дата добавления</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
    {% for sp in f.qs %}
      <tr>
        <td>{{ sp.id }}</td>
        <td>{{ sp.price }}</td>
        <td>{{ sp.category }}</td>
        <td>{{ sp.timestamp }}</td>
        <td>
            <a href="{% url 'spending:update' pk=sp.id %}">Изменить</a>
            <a href="{% url 'spending:delete' pk=sp.id %}">Удалить</a>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

{% endblock content %}

costs/templates/spending/update.html
{% extends "base_update.html" %}

{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block title %}
<h1>
Изменить трату
</h1>
{% endblock title %}